In [14]:
import tensorflow as tf
import numpy as np
import scipy


input = np.array([  [  [1., 2., 3.], [4., 5., 6.], [7.,8.,9.]   ], [  [1., 2., 3.], [4., 5., 6.], [7.,8.,9.]   ], [  [1., 2., 3.], [4., 5., 6.], [7.,8.,9.]   ]   ])

print(input)

filter_image = scipy.ndimage.filters.gaussian_filter(input, [1, 1, 0])

print(filter_image)

print('here')
g_img = np.random.rand(3,4,5)
print(g_img)
print(np.shape(g_img))
print(scipy.ndimage.shift(g_img, [1,0,0]))
print(g_img[:,:,0])

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
[[[2.2662213 3.2662213 4.2662213]
  [4.        5.        6.       ]
  [5.7337787 6.7337787 7.7337787]]

 [[2.2662213 3.2662213 4.2662213]
  [4.        5.        6.       ]
  [5.7337787 6.7337787 7.7337787]]

 [[2.2662213 3.2662213 4.2662213]
  [4.        5.        6.       ]
  [5.7337787 6.7337787 7.7337787]]]
here
[[[0.33236162 0.52490697 0.37123155 0.726592   0.16193511]
  [0.54850836 0.72476141 0.29241226 0.75900113 0.56383803]
  [0.24618776 0.59852254 0.91663467 0.45040472 0.75277576]
  [0.98958039 0.95166289 0.6963308  0.04479124 0.04986475]]

 [[0.89115964 0.86579977 0.34812306 0.22438011 0.9699748 ]
  [0.19913711 0.96179497 0.47753228 0.75300035 0.7811746 ]
  [0.82374426 0.46895631 0.63962821 0.05084098 0.10290127]
  [0.64983385 0.90493321 0.80291213 0.49651359 0.49307031]]

 [[0.16120286 0.97202778 0.57771724 0.6246083  0.88280442]
  [0.90618008 0.71557984 

In [21]:
x,y,r = np.where(input == 1.)
print(x)
print(y)
print(r)

[0 1 2]
[0 0 0]
[0 0 0]


In [20]:
g=1
print(np.size(g))


1


In [24]:
z = [1,2,3,4,5,6,7,8,9]
d = np.array(z).reshape(3,3)
print(d[0])

[1 2 3]


In [26]:
print(np.random.rand())

0.699169443511
